return {
  'folke/which-key.nvim',
  dependencies = { "nvim-tree/nvim-web-devicons" },
  event = "VeryLazy",
  opts = {
    preset = "modern",
    spec = {
      { "<leader>a", group = "Swap" },
      -- { "<leader>a_", hidden = true },
      { '<leader>c',  group = '[C]ode' },
      -- { '<leader>c_', hidden = true },
      { '<leader>d',  group = '[D]ocument' },
      -- { '<leader>d_', hidden = true },
      { '<leader>g',  group = '[G]it' },
      -- { '<leader>g_', hidden = true },
      { '<leader>f',  group = '[F]ind' },
      -- { '<leader>f_', hidden = true },
      { '<leader>h',  group = 'Git [H]unk' },
      -- { '<leader>h_', hidden = true },
      { '<leader>p',  group = '[P]roject' },
      -- { '<leader>p_', hidden = true },
      { '<leader>r',  group = '[R]est' },
      -- { '<leader>r_', hidden = true },
      { '<leader>s',  group = '[S]earch' },
      -- { '<leader>s_', hidden = true },
      { '<leader>t',  group = '[T]oggle' },
      -- { '<leader>t_', hidden = true },
      { '<leader>w',  group = '[W]orkspace' },
      -- { '<leader>w_', hidden = true },
      { '<leader>x',  group = 'Trouble' },
      -- { '<leader>x_', hidden = true },
      { '<leader>',   group = 'VISUAL <leader>', mode = 'v' },
      -- { '<leader>_',  hidden = true,             mode = 'v' },
      { '<leader>h',  group = 'Git [H]unk',      mode = 'v' },
      -- { '<leader>h_', hidden = true,             mode = 'v' },
    },
  },
}
